version: 2.1

# Orchestrate or schedule a set of jobs
workflows:
  build:
    jobs:
      - linux-arm64

jobs:
  linux-arm64:
    docker:
      - image: dockcross/linux-arm64
    steps:
      - checkout
      - run: |
          conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan
          conan install conanfile.txt
      - run: |
          cmake -E make_directory build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cd build
          cmake --build . --config Release
          ctest -C Release --output-on-failure
