version: 2.1

# Orchestrate or schedule a set of jobs
workflows:
  build:
    jobs:
      - linux-arm64

jobs:
  linux-arm64:
    docker:
      - image: dockcross/linux-arm64
    steps:
      - checkout
      - run: |
          cmake -E make_directory build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          ctest -C Release --output-on-failure
